import pandas as pd, numpy as np
P = '/Users/manasses/Documents/ChatGPT/Batalha de Agentes/'
df = pd.read_csv(P + 'data/extrato_sintetico.csv.gz', dtype={'id_usuario': str, 'descr': str})
df['descr'] = df['descr'].fillna(''); df['c'] = (df.vlr * 100).round().astype('int64')
has = lambda micro: set(df[df.nom_cate_micro == micro].id_usuario)
U = pd.DataFrame(index=sorted(df.id_usuario.unique()))
U['perfil'] = np.select([U.index.isin(has('Beneficio INSS')), U.index.isin(has('Pagamento de aluguel')), U.index.isin(has('Recebimento Aluguel')), U.index.isin(has('Financiamento de imovel'))],
                        ['INSS', 'PIX+alug', 'CLT+fin+recebe', 'CLT+fin'], 'CLT s/fin')
N = U.perfil.value_counts(); order = ['CLT+fin', 'CLT s/fin', 'INSS', 'PIX+alug', 'CLT+fin+recebe']
def sig(nome, mask):
    s = df[mask]; us = s.id_usuario.unique(); by = (U.loc[us].perfil.value_counts().reindex(order).fillna(0) / N.reindex(order))
    per = s.groupby('id_usuario').c.sum() / 100
    print(f'{nome:<34} clientes {len(us):>4} | R$/ano total {s.c.sum() / 100:>12,.0f} | mediana/cliente R$ {per.median():>8,.0f} | ' + ' '.join(f'{k}:{v:4.0%}' for k, v in by.items()))
mi, ma, d = df.nom_cate_micro, df.nom_cate_macro, df.descr
print('perfis:', N.reindex(order).to_dict())
print('--- USAR O CREDITO')
sig('fatura parcial ou minimo', (mi == 'Pagamento de fatura') & d.str.contains('parcial|minimo'))
sig('juros pagos', mi == 'Juros pagos')
sig('emprestimo pessoal/outros', mi.isin(['Emprestimos', 'Outros emprestimos']))
sig('renegociacao de divida', d.str.contains('reneg'))
sig('consignado', d.str.contains('consig'))
sig('compra parcelada', df.parcela_total > 1)
sig('financiamento imobiliario', mi == 'Financiamento de imovel')
print('--- CUSTOS EVITAVEIS / PRODUTOS')
sig('tarifas (anuidade, pacote, outras)', mi.isin(['Anuidade e pacote de servico', 'Outras tarifas financeiras']))
sig('seguros (todos)', mi.isin(['Seguros', 'Outros seguros']))
sig('seguro do cartao/prestamista', d.str.contains('seg cartao|seg credito|seg lis|prestam'))
sig('titulo de capitalizacao', mi == 'Titulo de capitalizacao')
sig('consorcio', mi == 'Consorcio')
sig('multa por atraso (contas)', mi == 'Multa por atraso')
sig('multa (veiculo)', mi == 'Multa')
sig('saque', ma == 'Saque')
print('--- ORGANIZAR O HOJE')
sig('assinaturas', ma == 'Assinaturas')
sig('delivery', ma == 'Delivery')
sig('transporte por app', ma == 'Transporte por app')
sig('restaurantes/cafe/padaria', ma == 'Restaurantes')
sig('gastos pequenos (<R$40, cartao/pix)', (df.tipo == 'S') & (df.c < 4000) & d.str.contains('cart credito|pix qrs') & ma.isin(['Restaurantes', 'Delivery', 'Mercado', 'Transporte por app', 'Outros gastos', 'Lazer']))
sig('lojas e sites', ma == 'Lojas e sites')
sig('viagens', ma == 'Viagens')
print('--- CONSTRUIR O AMANHA')
inv = d.str.contains('aplic|resgat|invest|poupan|cdb|tesouro|caixinha|cofrinho|previd|reserva|lci|lca|fundo')
print('linhas com termos de investimento/poupanca:', int(inv.sum()), '| exemplos:', d[inv].value_counts().head(8).to_dict())
sig('13o salario', mi == '13o salario'); sig('PLR', mi == 'Bonus PLR'); sig('aluguel recebido', mi == 'Recebimento Aluguel')
a = df[ma == 'Assinaturas']; k = a.groupby('id_usuario').descr.nunique()
print('servicos de assinatura por cliente: mediana', k.median(), '| max', k.max(), '| dist', k.value_counts().sort_index().to_dict())
print('assinaturas: valor muda ao longo do ano?', a.groupby(['id_usuario', 'descr']).c.nunique().gt(1).mean().round(3), '| servicos:', a.descr.value_counts().to_dict())
card = d.str.startswith('cart credito'); isf = mi == 'Pagamento de fatura'
g = df.assign(E=np.where(df.tipo == 'E', df.c, 0), S=np.where((df.tipo == 'S') & ~card, df.c, 0)).groupby(['id_usuario', 'anomes'])[['E', 'S']].sum()
neg = (g.E < g.S).groupby(level=0).sum(); U['meses_neg'] = neg.reindex(U.index).fillna(0)
U['saldo_neg'] = U.index.isin(set(df[df.saldo_apos < 0].id_usuario))
inc = df[df.tipo == 'E'].groupby(['id_usuario', 'anomes']).c.sum().unstack(fill_value=0); cv = (inc.std(axis=1) / inc.mean(axis=1))
U['cv_renda'] = cv.reindex(U.index)
print(U.groupby('perfil').agg(meses_fluxo_neg=('meses_neg', 'median'), com_saldo_neg=('saldo_neg', 'mean'), cv_renda=('cv_renda', 'median')).reindex(order).round(2).to_string())
